docs/features/features.md

Adding some docs (never linked out anywhere) about the features that JABS uses.
This commit is mostly to migrate some important docs from another place to where it belongs
The other docs were originally written by @pa-glen and have been updated to include the following:
* format change to markdown
* static objects features added
* counts for different subsets (which are controllable via UI)

Adding feature docs

---

src/project/project.py

Due to our recent release of the strain survey dataset, we should also allow the GUI to use mp4 files as videos.

Allow mp4 videos

---

src/feature_extraction/base_features/centroid_velocity.py
src/feature_extraction/base_features/point_speeds.py
src/feature_extraction/base_features/point_velocities.py
src/feature_extraction/features.py
src/feature_extraction/landmark_features/corner.py
src/feature_extraction/landmark_features/food_hopper.py
src/feature_extraction/segmentation_features/shape_descriptors.py
src/feature_extraction/social_features/social_distance.py
src/pose_estimation/__init__.py
src/pose_estimation/pose_est.py
src/pose_estimation/pose_est_v2.py
src/pose_estimation/pose_est_v3.py
src/pose_estimation/pose_est_v4.py
src/pose_estimation/pose_est_v5.py
src/ui/central_widget.py
src/version/__init__.py
src/video_stream/frame_annotation.py

Bug patches:
* Some pose masking did not properly threshold confidences
* Masking of keypoints not tiled correctly to x,y locations
* Pixel units never applied properly to some features
* FPS feature not applied to some segmentation features
* Adjusted angle features to be "mathematicians" angle (0 heading forward, + counter-clockwise)
Internal Change
* To avoid future confusion, all data is now represented internally as (x, y). Data is transformed at pose file read time. Cached data is always (x,y). Handful of incorrect comments were corrected/removed. Features were adjusted to remain correct.

Patching keypoint masking and cm units

---

README.md
environment.yml

This PR adds an `environment.yml` that produces a working conda environment across platforms and corresponding instructions in the README.
The only non-conda package that is used is for `PySide6` since `QtWebEngine` is not yet available for Qt 6.x on `conda-forge` (https://github.com/conda-forge/qt-webengine-feedstock/pull/46).
I didn't add anything to the docs in case you guys wanted to hold off on that before testing.

Add working `environment.yml`

---

docs/features/features.md
src/feature_extraction/features.py
src/feature_extraction/landmark_features/corner.py

Adding some features that get calculated and cached but not used in classifiers. These features are designed to enable traditional open field metrics to be calculated, as well as enabling more granular information about spatial location to be available for behavior calls.
Also found bugs with "nearest wall" feature, so still needed to bump the version
Exact Changes
* Added "distance to all walls" to be stored in feature cache file
* Added "average wall distance" to be stored in feature cache file
* Fixed a bug where mouse centroid would get px -> cm conversion twice in wall distance calculation
* Fixed a bug where wall corner points were assumed to be sorted, when they are not guaranteed to be sorted... by sorting them

OFA features

---

src/jabs/ui/archive_behavior_dialog.py
src/jabs/ui/main_control_widget.py
src/jabs/ui/main_window.py

closes #61
archiving the last behavior in a project behaves consistently with opening a project with no behaviors defined: a dialog is shown for the user to create a new behavior
dialog has been updated to allow user to quit JABS instead of saving a new behavior label (for example, if they open the wrong directory by mistake when selecting a project directory in the file open dialog)

61 archiving last behavior in a project should be handled better

---

src/jabs/ui/central_widget.py
src/jabs/ui/main_window.py
src/jabs/ui/project_loader_thread.py
src/jabs/utils/__init__.py

This change moves the loading of a project into a separate QThread
this prevents the "spinning beach ball" on macOS or the "this program is unresponsive" error on Windows
While the project is being loaded in its own thread, the main window will display an indeterminate progress bar animation 
If an exception is raised while loading a project, that Exception is passed back to the main UI thread and the string representation is displayed in an alert dialog 
also adds type hints in main_window.py

move project loading into a separate QThread to keep main UI thread responsive

---

src/jabs/pose_estimation/pose_est.py
src/jabs/pose_estimation/pose_est_v4.py
src/jabs/project/prediction_manager.py
src/jabs/project/project.py
src/jabs/project/video_labels.py
src/jabs/project/video_manager.py
src/jabs/scripts/convert_parquet.py
src/jabs/ui/central_widget.py
src/jabs/ui/classification_thread.py
src/jabs/ui/main_control_widget.py
src/jabs/ui/player_widget/player_widget.py
src/jabs/video_reader/frame_annotation.py

uses optional dataset in pose file "posest/external_identity_mapping", which is a 1D uint32 array
Note: I added code to check for this dataset in all pose file versions >= 4.  Since this is completely optional, I didn't want to create yet another pose file version. 
This ID is displayed in the JABS GUI for both mouse labels in the video and the identity drop down selector:
Additionally, this is saved in the prediction hdf5 files as "predictions/external_identity_mapping" as well as in the json files JABS uses to store labels internally.  I did not bump the prediction version, but am willing to do so.

add support for external ids 

---

pyproject.toml
src/jabs/ui/central_widget.py

fixes #90 
This bug is related to places where JABS was conflating the internal integer based identity with the string representation of the identity in the identity selection drop down
because we now support "external ids", there is a bit more work to do to clean up some places where it was using the string representation and not the internal integer id
This merge request fixes the immediate issue, but more work is needed to clean up, which will be in a followup pull request

fix issue #90

---

src/jabs/constants.py
src/jabs/ui/main_window.py

closes #92 
Uses QSettings to persist the user's acceptance of the license agreement 
also saves the JABS version at the time of license acceptance so we can force re-acceptance in the future if we want (for example, if license changes in version X we could force anyone that accepted license terms prior to version X to re-confirm)
Also use QSettings to keep track of the most recent projects.  Adds a File->Open Recent menu that is populated with the most recently opened projects (up to 5)

persist acceptance of license agreement

---

ruff.toml
src/jabs/__init__.py
src/jabs/types/__init__.py
src/jabs/types/classifier_types.py
src/jabs/types/units.py
src/jabs/utils/__init__.py
src/jabs/utils/sampleposeintervals.py
src/jabs/utils/utilities.py
src/jabs/version/__init__.py
src/jabs/video_reader/__init__.py
src/jabs/video_reader/frame_annotation.py
src/jabs/video_reader/utilities.py
src/jabs/video_reader/video_reader.py

first round of ruff linter error fixes
src/jabs/utils
src/jabs/version
src/jabs/video_reader
src/jabs/types
also sets target version to py310 since we want to ensure code is compatible with Python 3.10 or greater. Older versions are no longer supported.

fix ruff check errors

---

src/jabs/project/__init__.py
src/jabs/project/export_training.py
src/jabs/project/feature_manager.py
src/jabs/project/prediction_manager.py
src/jabs/project/project.py
src/jabs/project/project_utils.py
src/jabs/project/read_training.py
src/jabs/project/settings_manager.py
src/jabs/project/track_labels.py
src/jabs/project/video_labels.py
src/jabs/project/video_manager.py

fixes ruff check errors
also fixes some docstrings that were either formatted poorly by the automated doctoring style formatting or were lacking in content

fix ruff check errors in src/jabs/project

---

src/jabs/project/project.py
src/jabs/resources/docs/user_guide/user_guide.md

saves the username in the annotation .json files
currently is saved in a top-level field called "labeler" (I could change this to "username" or "user" based on group consensus)

save username in annotation .json files

---

pyproject.toml
src/jabs/ui/stacked_timeline_widget/stacked_timeline_widget.py

fix bug with orphan QFrames
this was quite noticeable on windows -- when in "Selected Animal" mode for the stacked timeline widget the QFrames for the hidden timelines for the non-active identities became parentless and showed up as tiny empty windows
This fixes it so they continue to have the MainWindow as a parent when hidden.

fix orphan qframes

---

src/jabs/ui/player_widget/frame_widget.py
src/jabs/ui/player_widget/player_widget.py

refactors the player widget to move the FrameWidget into its own file in the jabs.ui.player_widget package
also fixes bug where using a trackpad or mouse scroll gesture to move the position slider would not seek the video to the frame corresponding to the new slider position 
adds additional type hints to PlayerWidget

Refactor player widget

---

src/jabs/pose_estimation/pose_est_v4.py

I had a project that included a few videos where the mice were hidden under nesting material for the entire 1 minute segment.  This causes an exception and prevented JABS from loading the project. 
This change makes it so that JABS won't raise an exception when reading the pose file so the project can still be opened. 
Not sure if there might be other bugs when training / predicting on this project, but for now this will at least allow us to open the project and label other videos.

fix exception loading pose file with no identities

---

src/jabs/ui/central_widget.py
src/jabs/ui/classification_thread.py
src/jabs/ui/main_control_widget.py
src/jabs/ui/main_window.py
src/jabs/ui/training_thread.py

previously, if an exception were raised during training or classification, the GUI would get stuck with the progress dialog open. The only remedy was to force quit the application. This was also confusing to users, because unless they looked in the terminal and saw the exception stack trace, they had no indication something was wrong other than the progress bar not moving for a long period of time. 
This change dismisses the progress bar and displays an alert dialog with a message about the exception that occurred. Also the stack trace is printed to the terminal to aid with debugging. In the future we could have CentralWidget treat different types of exceptions differently -- for example if there is a problem with data we could give the user a different error message (and not print the …

make the GUI handle exceptions raised in training and classification threads

---

src/jabs/ui/video_list_widget.py

currentRow() and setCurrentRow() in a QListWidget operate on all items, not just visible ones. 
This resulted in a bug when using the previous and next video keyboard shortcuts while a filter is applied to the video list.
This change searches forward or backwards from the current video to find the next or previous visible video to account for filtering

fix previous and next video keyboard control when some video filenames are filtered

---

src/jabs/pose_estimation/pose_est.py

handle more types of errors when trying to read cached convex hull arrays
also uses joblib for reading/writing pickle file (used elsewhere in JABS rather than the pickle module because it handles numpy arrays better. changing here just for consistency )

deal with more errors reading cached convex hulls

---

src/jabs/behavior_search/__init__.py
src/jabs/behavior_search/behavior_search_util.py
src/jabs/ui/behavior_search_dialog.py
src/jabs/ui/central_widget.py
src/jabs/ui/search_bar_widget.py
src/jabs/ui/stacked_timeline_widget/label_overview_widget/label_overview_util.py
src/jabs/ui/stacked_timeline_widget/stacked_timeline_widget.py
tests/test_behavior_search.py

Implement timeline annotation search with ability to specify a contiguous frame count range. Also randomized y axis placement of search results on timeline to avoid confusion if search hits overlap in time. Loading available tag strings is done in a background thread for the search dialog to avoid blocking the UI.

implement timeline annotation search

---

pyproject.toml
src/jabs/feature_extraction/base_features/angles.py
src/jabs/feature_extraction/feature_base_class.py
src/jabs/feature_extraction/features.py
tests/feature_modules/test_corner_features.py

reverts name change of window operations for circular features to restore backwards compatibility with previously exported training data

revert name change of window op for circular features

---

vm/behavior-classify-batch.sh

JABS classify command was renamed from `classify` to `jabs-classify` but this batch script was never updated

fix classify command in batch script

---

.gitignore
src/jabs/pose_estimation/pose_est.py
src/jabs/project/__init__.py
src/jabs/project/project.py
src/jabs/project/timeline_annotations.py
src/jabs/project/video_labels.py
src/jabs/project/video_manager.py
src/jabs/resources/docs/user_guide/user_guide.md
src/jabs/ui/annotation_edit_dialog.py
src/jabs/ui/central_widget.py
src/jabs/ui/label_count_widget.py
src/jabs/ui/main_control_widget.py
src/jabs/ui/player_widget/overlays/annotation_info_dialog.py
src/jabs/ui/player_widget/overlays/annotation_overlay.py
src/jabs/ui/player_widget/player_widget.py
src/jabs/ui/stacked_timeline_widget/frame_labels_widget.py
src/jabs/ui/stacked_timeline_widget/stacked_timeline_widget.py
src/jabs/ui/util.py
tests/timeline_annotations.py

Implements KLAUS-184
This PR adds the ability to create new Timeline Annotations through the JABS GUI as well as edit or delete existing Timeline Annotations.
A new button is added to the "Labeling" button group in the MainControlWidget:
This button becomes active when JABS is in "Select Mode" and one or more frames are selected
Clicking it will open the Timeline Annotation Editor:
Entering a valid tag is required for the "OK" button to become active. If the user enters invalid text for the tag, for example special characters, the text color will change red to indicate the value is not valid.
Clicking the color swatch will let the user pick a different color for the annotation. This is the background color used to draw the overlay in the video player for the annotation. 
The Description …

Add timeline annotation editor

---

tests/__init__.py
tests/feature_modules/__init__.py
tests/feature_modules/base.py
tests/feature_modules/test_food_hopper.py
tests/feature_modules/test_lixit_distance.py
tests/feature_tests/seg_test_utils.py
tests/feature_tests/test_hu_moments.py
tests/project/__init__.py
tests/project/test_prediction_manager.py
tests/project/test_project_path.py
tests/test_base_features/test_segmentation.py
tests/test_pose_ancillary.py
tests/test_pose_file.py
tests/test_social_features/test_signal_processing.py
tests/test_track_labels.py

This PR applied automated and straight-forward manual fixes for linting and formatting rules on the tests directory. It does not get all of the linting rules to pass on the directory.

Applying simple formatting and linting rules to tests

---

README.md
src/jabs/project/project.py
src/jabs/project/settings_manager.py
src/jabs/project/video_labels.py
src/jabs/scripts/cli.py
tests/project/test_project.py
tests/project/test_settings_manager.py
tests/test_video_labels.py

Note: branch name is misleading, should be *rename-behavior-util*
add cli utility for renaming a behavior in an existing JABS project
usage:
`jabs-cli rename-behavior <project dir> <old behavior name> <new behavior name>`

Rename behavior utility
