src/version/__init__.py

I didn't bump the version on the last pull request

bump version

---

classify.py
vm/behavior-classify-batch.sh

The script for inference on the cluster was modified. This branch just reflects the modifications.
Major changes:
* Removed forced XGBoost classifier selection (overrode trained classifier selection)
* Changes requested resources to better reflect actual needs
* New function for detecting pose file version rather than repeated ifs

Update cluster script

---

tests/test_pose_file.py

Changes 2 test assertions to allow nans in comparison.

Patch 0.17.3 tests

---

src/feature_extraction/landmark_features/corner.py

Patched to address https://github.com/KumarLabJax/JABS-behavior-classifier/issues/50
Changes:
* Bugfix on un-initialized wall length
* Fix of wall distances always being positive (instead of all turning negative when mouse is outside the corners)

Corner feature patches

---

src/jabs/feature_extraction/feature_base_class.py
src/jabs/feature_extraction/segmentation_features/hu_moments.py
tests/feature_tests/seg_test_utils.py
tests/feature_tests/test_hu_moments.py
tests/feature_tests/test_moments.py
vm/behavior-classifier-vm-gui.def
vm/behavior-classifier-vm.def

Changes:
* Updating container definitions to use poetry
* builds wheel
* installs wheel
* cleans up
* Removing 2 warnings from newer lib versions
* numpy arr into scalar (was arr of length 1)
* scipy warning for nan values in circular stats calls
* fixing some segmentation tests
* these were never adequately checked because they were missed by the "discover". They still need some work to actually test well, but this is good enough for now...

Packaging feedback

---

README.md
jabs.bat
launch_jabs.bat
setup_windows.bat

update windows scripts

---

src/jabs/project/project.py
src/jabs/ui/main_control_widget.py
src/jabs/ui/main_window.py

update project.json when adding new behavior labels

---

setup_windows.bat

the setup_windows.bat script was only checking for python 3.10
update to also check for 3.11 and 3.12
also add a command line parameter to skip the python version check and just try to install

Update setup_windows.bat to also support python 3.11 and 3.12

---

setup_windows.bat

fixes syntax error in windows_setup.bat, also correctly finds Python version

fix some issues with the windows setup script

---

src/jabs/feature_extraction/features.py

truncate feature h5 file when recreating

---

src/jabs/feature_extraction/landmark_features/corner.py

fixes deprecation warning in corner.py
```
tests/feature_modules/test_corner_features.py: 5329 warnings
/Users/gbeane/projects/jabs/JABS-behavior-classifier/src/jabs/feature_extraction/landmark_features/corner.py:96: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
wall_dist = np.abs(np.cross(centroid_point - p1, p2 - p1))  # / np.linalg.norm(p2 - p1)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
spot checking 
wall_distances/wall_0
before change:
after change:

fix numpy 2 deprecation warning

---

src/jabs/ui/main_control_widget.py

Very minor change to add tooltips that include hotkeys for label editing.

add tooltips for labeling hotkeys to the relevant buttons

---

src/jabs/ui/__init__.py
src/jabs/ui/about_dialog.py
src/jabs/ui/archive_behavior_dialog.py
src/jabs/ui/central_widget.py
src/jabs/ui/classification_thread.py
src/jabs/ui/frame_labels_widget.py
src/jabs/ui/global_inference_widget.py
src/jabs/ui/identity_combo_box.py
src/jabs/ui/k_fold_slider_widget.py
src/jabs/ui/label_count_widget.py
src/jabs/ui/license_dialog.py
src/jabs/ui/main_control_widget.py
src/jabs/ui/main_window.py
src/jabs/ui/manual_label_widget.py
src/jabs/ui/player_widget/__init__.py
src/jabs/ui/player_widget/player_thread.py
src/jabs/ui/player_widget/player_widget.py
src/jabs/ui/prediction_vis_widget.py
src/jabs/ui/timeline_label_widget.py
src/jabs/ui/training_thread.py
src/jabs/ui/user_guide_viewer_widget/__init__.py
src/jabs/ui/user_guide_viewer_widget/user_guide_dialog.py
src/jabs/ui/video_list_widget.py

round 2 of fixing `ruff check` linting errors:
addresses ruff linting errors in /src/jabs/ui

fix ruff check linting errors in src/jabs/ui

---

src/jabs/scripts/__init__.py
src/jabs/scripts/classify.py
src/jabs/scripts/convert_parquet.py
src/jabs/scripts/generate_features.py
src/jabs/scripts/gui_entrypoint.py
src/jabs/scripts/initialize_project.py
src/jabs/scripts/stats.py

fixes ruff check errors for files in src/jabs/scripts directory

fix ruff errors in src/jabs/scripts

---

src/jabs/feature_extraction/landmark_features/landmark_group.py
src/jabs/pose_estimation/__init__.py
src/jabs/pose_estimation/pose_est.py
src/jabs/pose_estimation/pose_est_v2.py
src/jabs/pose_estimation/pose_est_v3.py
src/jabs/pose_estimation/pose_est_v4.py
src/jabs/pose_estimation/pose_est_v5.py
src/jabs/pose_estimation/pose_est_v6.py
src/jabs/video_reader/frame_annotation.py

more fixes for ruff linter errors
also fixes src/jabs/feature_extraction/landmark_features/landmark_group.py due to renamed pose property

fix ruff check errors for src/jabs/pose_estimation

---

tests/project/test_project.py

We need to account for labeler in the test. Also a lot of ruff check/format changes

fix test_save_annotations test by adding labeler

---

src/jabs/behavior_search/behavior_search_util.py
src/jabs/resources/docs/user_guide/user_guide.md
src/jabs/ui/central_widget.py
src/jabs/ui/main_window.py
src/jabs/ui/stacked_timeline_widget/label_overview_widget/label_overview_widget.py
src/jabs/ui/stacked_timeline_widget/label_overview_widget/manual_label_widget.py
src/jabs/ui/stacked_timeline_widget/stacked_timeline_widget.py

ctrl+a/cmd+a will now select all frames in the current timeline for labeling

add select all feature

---

src/jabs/project/video_labels.py

fix test errors

---

src/jabs/classifier/classifier.py
src/jabs/project/project.py
src/jabs/project/track_labels.py
src/jabs/ui/central_widget.py
src/jabs/ui/stacked_timeline_widget/label_overview_widget/manual_label_widget.py

uses "unfragmented labels" for label count summary in UI
uses "fragmented label count" for determining if training button should be enabled since this reflects labels available for training

Fix yoda 179

---

pyproject.toml
src/jabs/ui/behavior_search_dialog.py

encountered this error if there is a completely unlabeled video (no annotation JSON file)
```
Traceback (most recent call last):
File "/Users/gbeane/projects/jabs/JABS-behavior-classifier/src/jabs/ui/behavior_search_dialog.py", line 39, in run
if "annotations" in anno_dict:
^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Fix search bug if no json

---

src/jabs/feature_extraction/features.py
src/jabs/feature_extraction/social_features/social_distance.py

fix issue 167

---

pyproject.toml
src/jabs/classifier/classifier.py

fixing problem encountered by Pavan
was partially fixed previously, but missed removing infs in a couple spots

remove infs from features before training or classifying

---

src/jabs/project/project.py
src/jabs/project/read_training.py
src/jabs/project/session_tracker.py
src/jabs/project/settings_manager.py
src/jabs/ui/classification_thread.py

- make some file writes atomic
- add some comments
- fix some IDE type checking warnings for incorrectly inferred type
- add unfragmented labels to archived behavior file

misc. minor changes
